[2025-03-11T07:14:40.514+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.fetch_purchases manual__2025-03-11T07:14:36+00:00 [queued]>
[2025-03-11T07:14:40.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.fetch_purchases manual__2025-03-11T07:14:36+00:00 [queued]>
[2025-03-11T07:14:40.519+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-11T07:14:40.527+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): fetch_purchases> on 2025-03-11 07:14:36+00:00
[2025-03-11T07:14:40.533+0000] {standard_task_runner.py:57} INFO - Started process 2950 to run task
[2025-03-11T07:14:40.537+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_bronze_layer_dag', 'fetch_purchases', 'manual__2025-03-11T07:14:36+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/ingesting_pipeline.py', '--cfg-path', '/tmp/tmpt7rzua45']
[2025-03-11T07:14:40.539+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask fetch_purchases
[2025-03-11T07:14:40.571+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_bronze_layer_dag.fetch_purchases manual__2025-03-11T07:14:36+00:00 [running]> on host 41ccd9d1769c
[2025-03-11T07:14:40.905+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='ingest_bronze_layer_dag' AIRFLOW_CTX_TASK_ID='fetch_purchases' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T07:14:36+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T07:14:36+00:00'
[2025-03-11T07:14:40.913+0000] {base.py:73} INFO - Using connection ID 'postgres_source_db' for task execution.
[2025-03-11T07:14:40.919+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingesting_pipeline.py", line 69, in fetch_purchases
    raise ValueError("backfill_start_date and backfill_end_date must be provided if is_full_refresh is True")
ValueError: backfill_start_date and backfill_end_date must be provided if is_full_refresh is True
[2025-03-11T07:14:40.929+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ingest_bronze_layer_dag, task_id=fetch_purchases, execution_date=20250311T071436, start_date=20250311T071440, end_date=20250311T071440
[2025-03-11T07:14:40.937+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 107 for task fetch_purchases (backfill_start_date and backfill_end_date must be provided if is_full_refresh is True; 2950)
[2025-03-11T07:14:40.972+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-11T07:14:40.986+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
