[2025-03-12T07:14:22.165+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline manual__2025-03-12T07:13:50+00:00 [queued]>
[2025-03-12T07:14:22.169+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline manual__2025-03-12T07:13:50+00:00 [queued]>
[2025-03-12T07:14:22.169+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-12T07:14:22.258+0000] {taskinstance.py:1382} INFO - Executing <Task(TriggerDagRunOperator): trigger_hourly_pipeline> on 2025-03-12 07:13:50+00:00
[2025-03-12T07:14:22.260+0000] {standard_task_runner.py:57} INFO - Started process 19290 to run task
[2025-03-12T07:14:22.262+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_bronze_and_silver_layer', 'trigger_hourly_pipeline', 'manual__2025-03-12T07:13:50+00:00', '--job-id', '1557', '--raw', '--subdir', 'DAGS_FOLDER/5mins_processing_pipeline.py', '--cfg-path', '/tmp/tmpl24gkmvj']
[2025-03-12T07:14:22.264+0000] {standard_task_runner.py:85} INFO - Job 1557: Subtask trigger_hourly_pipeline
[2025-03-12T07:14:22.288+0000] {task_command.py:416} INFO - Running <TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline manual__2025-03-12T07:13:50+00:00 [running]> on host c8e526380ef3
[2025-03-12T07:14:22.313+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'trigger_hourly_pipeline', field 'conf'. Template: {'source': '5min_trigger', 'is_full_refresh': "{{ ti.xcom_pull(task_ids='check_hourly_data_freshness')['is_full_refresh'] }}", '5mins_is_full_refresh': "{{ ti.xcom_pull(task_ids='check_hourly_data_freshness')['5mins_is_full_refresh'] }}", '5mins_start_date': "{{ ti.xcom_pull(task_ids='check_hourly_data_freshness')['5mins_start_date'] }}", '5mins_end_date': "{{ ti.xcom_pull(task_ids='check_hourly_data_freshness')['5mins_end_date'] }}"}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 167, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 167, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/runtime.py", line 859, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute '5mins_is_full_refresh'
[2025-03-12T07:14:22.316+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 167, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 167, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/runtime.py", line 859, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute '5mins_is_full_refresh'
[2025-03-12T07:14:22.322+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=process_bronze_and_silver_layer, task_id=trigger_hourly_pipeline, execution_date=20250312T071350, start_date=20250312T071422, end_date=20250312T071422
[2025-03-12T07:14:22.327+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1557 for task trigger_hourly_pipeline ('dict object' has no attribute '5mins_is_full_refresh'; 19290)
[2025-03-12T07:14:22.369+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-12T07:14:22.380+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
