[2025-03-12T10:05:12.455+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.transform_silver_5mins_incremental scheduled__2025-03-12T10:00:00+00:00 [queued]>
[2025-03-12T10:05:12.464+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.transform_silver_5mins_incremental scheduled__2025-03-12T10:00:00+00:00 [queued]>
[2025-03-12T10:05:12.464+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-12T10:05:12.624+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): transform_silver_5mins_incremental> on 2025-03-12 10:00:00+00:00
[2025-03-12T10:05:12.628+0000] {standard_task_runner.py:57} INFO - Started process 28686 to run task
[2025-03-12T10:05:12.630+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_bronze_and_silver_layer', 'transform_silver_5mins_incremental', 'scheduled__2025-03-12T10:00:00+00:00', '--job-id', '2333', '--raw', '--subdir', 'DAGS_FOLDER/5mins_processing_pipeline.py', '--cfg-path', '/tmp/tmpgonzgpoj']
[2025-03-12T10:05:12.632+0000] {standard_task_runner.py:85} INFO - Job 2333: Subtask transform_silver_5mins_incremental
[2025-03-12T10:05:12.659+0000] {task_command.py:416} INFO - Running <TaskInstance: process_bronze_and_silver_layer.transform_silver_5mins_incremental scheduled__2025-03-12T10:00:00+00:00 [running]> on host c8e526380ef3
[2025-03-12T10:05:12.708+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='process_bronze_and_silver_layer' AIRFLOW_CTX_TASK_ID='transform_silver_5mins_incremental' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-12T10:00:00+00:00'
[2025-03-12T10:05:12.710+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-12T10:05:12.713+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt/playstudio_project && export WAREHOUSE_HOST=None && export WAREHOUSE_PASSWORD=None && export WAREHOUSE_USER=None && dbt run --select tag:silver_5mins_incremental --target prod']
[2025-03-12T10:05:12.735+0000] {subprocess.py:86} INFO - Output:
[2025-03-12T10:05:14.197+0000] {subprocess.py:93} INFO - [0m10:05:14  Running with dbt=1.7.18
[2025-03-12T10:05:14.306+0000] {subprocess.py:93} INFO - [0m10:05:14  Registered adapter: postgres=1.7.18
[2025-03-12T10:05:14.316+0000] {subprocess.py:93} INFO - [0m10:05:14  Unable to do partial parsing because of a version mismatch
[2025-03-12T10:05:14.790+0000] {subprocess.py:93} INFO - [0m10:05:14  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-12T10:05:14.790+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-12T10:05:14.790+0000] {subprocess.py:93} INFO - - models.playstudio_project.bronze_layer
[2025-03-12T10:05:14.810+0000] {subprocess.py:93} INFO - [0m10:05:14  Found 3 models, 2 sources, 0 exposures, 0 metrics, 402 macros, 0 groups, 0 semantic models
[2025-03-12T10:05:14.810+0000] {subprocess.py:93} INFO - [0m10:05:14
[2025-03-12T10:05:30.886+0000] {subprocess.py:93} INFO - [0m10:05:30
[2025-03-12T10:05:30.888+0000] {subprocess.py:93} INFO - [0m10:05:30  Finished running  in 0 hours 0 minutes and 16.07 seconds (16.07s).
[2025-03-12T10:05:30.889+0000] {subprocess.py:93} INFO - [0m10:05:30  Encountered an error:
[2025-03-12T10:05:30.889+0000] {subprocess.py:93} INFO - Database Error
[2025-03-12T10:05:30.889+0000] {subprocess.py:93} INFO -   could not translate host name "local" to address: Temporary failure in name resolution
[2025-03-12T10:05:30.889+0000] {subprocess.py:93} INFO - 
[2025-03-12T10:05:32.163+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-03-12T10:05:32.177+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-03-12T10:05:32.180+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=process_bronze_and_silver_layer, task_id=transform_silver_5mins_incremental, execution_date=20250312T100000, start_date=20250312T100512, end_date=20250312T100532
[2025-03-12T10:05:32.192+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2333 for task transform_silver_5mins_incremental (Bash command failed. The command returned a non-zero exit code 2.; 28686)
[2025-03-12T10:05:32.202+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-12T10:05:32.219+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
